Repository 3rd-wanted-pre-onboarding-teamA/payHere-Wanted-A, pull requests merged in 2022-07, with the labels that each got.

#12 Feat: initial setting
  .gitignore
  client/index.ejs
  index.js
  package.json
  pay_here_account_book.sql
  server/routes/accountBook/create.js
  server/routes/auth/newUser.js
  server/routes/index.js
Labels: feature

#17 Feat: DB 연결 정보 모듈
  DB/dbConnect.js
  DB/pay_here_account_book.sql
  package-lock.json
  package.json
Labels: feature

#22 Feat: 가계부 리스트 구현
  public/css/list.css
  public/images/delete.png
  public/images/detail.png
  public/images/update.png
  public/js/list.js
  server/routes/accountBook/list.js
  server/routes/index.js
  views/list.ejs
Labels: feature

#23 Feat: 가계부 삭제 목록 구현
  public/css/deletedList.css
  public/images/restore.png
  server/routes/accountBook/deletedList.js
  server/routes/index.js
  views/deletedList.ejs
Labels: feature

#24 Feat: 삭제한 가계부 복원
  public/js/deletedList.js
  server/routes/accountBook/deletedList.js
  server/routes/accountBook/list.js
  server/routes/accountBook/restore.js
  server/routes/index.js
  views/deletedList.ejs
Labels: feature

#26 [Backend] Feature/사용자 회원가입 및 로그인, 인증 유효성 확인 위한 JWT 토큰 생성
  index.js
  models/auth.js
  package-lock.json
  package.json
  server/routes/auth/login.js
  server/routes/auth/newUser.js
  server/routes/auth/signUp.js
  server/routes/auth/token.js
  server/routes/index.js
  server/util/generateToken.js
  server/util/validateJwt.js
Labels: feature

#21 Feat: 메인 api 구현 - 가계부 생성
  data/accountBook.js
  server/routes/accountBook/create.js
  server/routes/accountBook/modify.js
  server/routes/accountBook/remove.js
  server/routes/index.js
  views/create.ejs
Labels: feature

#27 Refactor: 파일 구조 변경, app.js 클래스화
  app.js
  index.js
  package-lock.json
  package.json
  server.js
  server/controllers/accountBook.controller.js
  server/db/config.js
  server/db/pay_here_account_book.sql
  server/routes/accountBook.route.js
  server/routes/accountBook/create.js
  server/routes/accountBook/deletedList.js
  server/routes/accountBook/detail.js
  server/routes/accountBook/list.js
  server/routes/accountBook/modify.js
  server/routes/accountBook/remove.js
  server/routes/accountBook/restore.js
  server/routes/auth.route.js
  server/routes/auth/login.js
  server/routes/auth/signUp.js
  server/routes/auth/token.js
  server/routes/index.js
  server/services/accountBook.service.js
Labels: refactoring

#28 [backend] Refactor: 디렉토리 설계 수정에 따른 auth 로직 변경
  server/controllers/auth.controller.js
  server/routes/auth.route.js
  server/routes/index.js
  server/services/auth.service.js
  server/util/authValidator.js
Labels: refactoring

#29 Refactor: 가계부 CRUD 관련 코드 리팩토링
  server/controllers/accountBook.controller.js
  server/routes/accountBook.route.js
  server/services/accountBook.service.js
Labels: refactoring

#30 [Backend] Feature/회원가입 시 잔액 DB에 삽입하는 기능 추가
  server/controllers/auth.controller.js
  server/services/auth.service.js
  server/util/authValidator.js
Labels: feature

#34 Feat: 가계부 api test
  package-lock.json
  package.json
  server/test/accountBook.spec.js
Labels: feature

#33 Feature/ 회원가입, 로그인, 마이페이지 ejs 구현
  public/css/login.css
  public/css/mypage.css
  public/css/signUp.css
  public/js/login.js
  public/js/logout.js
  public/js/mypage.js
  public/js/signup.js
  server/controllers/auth.controller.js
  server/db/pay_here_account_book.sql
  server/routes/auth.route.js
  server/services/auth.service.js
  server/util/authValidator.js
  server/util/validateJwt.js
  views/login.ejs
  views/myage.ejs
  views/signup.ejs
Labels: feature

#35 Document/update readme syoungee
  README.md
Labels: documentation

#36 Feature/ auth, accountBook 컨트롤러 로직 구현 및 accountBook view파일 생성
  DB/dbConnect.js
  DB/pay_here_account_book.sql
  README.md
  app.js
  data/accountBook.js
  index.js
  package-lock.json
  package.json
  public/css/deletedList.css
  public/css/detail.css
  public/css/list.css
  public/css/login.css
  public/css/mypage.css
  public/css/signUp.css
  public/images/add.png
  public/images/delete.png
  public/images/detail.png
  public/images/logout.png
  public/images/restore.png
  public/images/trash.png
  public/images/update.png
  public/images/user.png
  public/js/deletedList.js
  public/js/list.js
  public/js/login.js
  public/js/logout.js
  public/js/mypage.js
  public/js/signup.js
  server.js
  server/controllers/accountBook.controller.js
  server/controllers/auth.controller.js
  server/db/config.js
  server/db/pay_here_account_book.sql
  server/routes/accountBook.route.js
  server/routes/accountBook/create.js
  server/routes/auth.route.js
  server/routes/auth/newUser.js
  server/routes/index.js
  server/services/accountBook.service.js
  server/services/auth.service.js
  server/test/accountBook.spec.js
  server/util/authValidator.js
  server/util/generateToken.js
  server/util/validateJwt.js
  views/create.ejs
  views/deletedList.ejs
  views/detail.ejs
  views/list.ejs
  views/login.ejs
  views/myage.ejs
  views/signup.ejs
Labels: feature

#37 Update README.md
  README.md
Labels: documentation

#38 Update README.md
  README.md
Labels: documentation

#39 Update README.md
  README.md
Labels: documentation

#40 Refactor/로그인 및 마이페이지 기능 로직 수정
  public/css/join.css
  public/css/login.css
  public/css/mypage.css
  public/js/join.js
  public/js/login.js
  public/js/logout.js
  public/js/mypage.js
  server/controllers/auth.controller.js
  server/db/pay_here_account_book.sql
  server/routes/auth.route.js
  server/services/auth.service.js
  server/util/authValidator.js
  server/util/validateJwt.js
  views/join.ejs
  views/login.ejs
  views/mypage.ejs
Labels: refactoring

#42 수정,삭제 view 반영
  public/css/create.css
  public/css/update.css
  public/js/create.js
  public/js/list.js
  public/js/update.js
  server/controllers/accountBook.controller.js
  server/routes/accountBook.route.js
  server/services/accountBook.service.js
  views/create.ejs
  views/list.ejs
  views/update.ejs
Labels: refactoring, feature

#43 Feat: 에러 핸들링
  app.js
  data/accountBook.js
  server/controllers/accountBook.controller.js
  server/controllers/auth.controller.js
  server/services/accountBook.service.js
  views/error.ejs
Labels: refactoring

#44 Refactor: Readme REST API 수정
  README.md
Labels: refactoring

#46 Upgrade: JWT 토큰 저장 장소 변경(local storage -> cookie)
  public/js/join.js
  public/js/login.js
  public/js/logout.js
  server/controllers/auth.controller.js
  server/services/auth.service.js
  server/util/validateJwt.js
  views/mypage.ejs
Labels: refactoring

#48 Refactor: user 관련 페이지 view 수정
  public/css/join.css
  public/css/login.css
  public/css/mypage.css
  views/join.ejs
  views/login.ejs
  views/mypage.ejs
Labels: refactoring

#49 Refactor: 가계부 관련 view 수정
  public/css/create.css
  public/css/detail.css
  public/css/update.css
  views/create.ejs
  views/update.ejs
Labels: refactoring

#50 Feature/mypage syoungee
  public/css/create.css
  public/css/deletedList.css
  public/css/detail.css
  public/css/join.css
  public/css/list.css
  public/css/login.css
  public/css/mypage.css
  public/css/update.css
  public/js/list.js
  public/js/mypage.js
  server/controllers/auth.controller.js
  views/list.ejs
  views/login.ejs
  views/mypage.ejs
Labels: feature

#51 Refactor: front 수정
  public/css/create.css
  public/css/join.css
  public/css/login.css
  public/css/update.css
  public/js/deletedList.js
  public/js/join.js
  public/js/list.js
  public/js/login.js
  public/js/update.js
  server/controllers/accountBook.controller.js
  server/routes/accountBook.route.js
  views/create.ejs
  views/login.ejs
  views/update.ejs
Labels: refactoring

#54 Refactor: 에러 코드 수정, index 페이지 설정
  app.js
  public/js/list.js
  public/js/logout.js
  server/controllers/accountBook.controller.js
  server/db/error.js
  server/routes/index.js
  server/services/accountBook.service.js
  views/error.ejs
  views/index.ejs
Labels: refactoring

#52 Upgrade: 엑세스 토큰 재발급 로직 변경
  server/util/validateJwt.js
Labels: refactoring

#55 Refactor: 가계부 테스트 코드 수정
  package-lock.json
  package.json
  server/controllers/accountBook.controller.js
  server/test/accountBook.spec.js
Labels: TDD

#57 Refactor: writer 추가
  app.js
  server/controllers/accountBook.controller.js
  server/controllers/auth.controller.js
  server/routes/accountBook.route.js
  server/services/accountBook.service.js
  server/services/auth.service.js
  server/util/authValidator.js
  server/util/generateToken.js
  server/util/validateJwt.js
Labels: refactoring

#59 Refactor: 날짜 입력받게 수정
  public/css/create.css
  public/css/update.css
  public/js/create.js
  public/js/update.js
  server/controllers/accountBook.controller.js
  server/db/pay_here_account_book.sql
  server/services/accountBook.service.js
  views/create.ejs
  views/deletedList.ejs
  views/list.ejs
  views/update.ejs
Labels: refactoring

#60 Refactor: auth/ 관련 API 에러 시 error.ejs 렌더링으로 수정
  server/controllers/auth.controller.js
Labels: refactoring

#62 Refactor: 날짜 입력받는 부분 추가 수정
  server/controllers/accountBook.controller.js
  server/services/accountBook.service.js
Labels: refactoring

#64 Refactor: 가계부 삭제, 복원에 따른 잔액 변경 트리거 수정
  server/db/pay_here_account_book.sql
  server/services/accountBook.service.js
Labels: refactoring

#67 Refactor: detail 날짜 변수 수정
  server/controllers/accountBook.controller.js
  views/detail.ejs
  views/error.ejs
  views/login.ejs
  views/mypage.ejs
Labels: refactoring

#68 Refactor: 가계부 날짜 입력 받는 받는 거에 따른 테스트코드 수정
  server/test/accountBook.spec.js
Labels: refactoring

#69 Test: 유저 관련 TDD 작성
  package-lock.json
  package.json
  server/test/auth.spec.js
Labels: TDD

#70 Test: 유저 관련 테스트 코드 작성
  package-lock.json
  package.json
  server/test/auth.spec.js
Labels: TDD

#71 Refactor: 테스트 코드 수정
  server/test/accountBook.spec.js
Labels: TDD

#73 유저 테스트 코드 수정
  server/test/auth.spec.js
  server/test/auth.utils.js
Labels: TDD
